import { ReactElement } from 'react';
import Head from 'next/head';
import HomePage from './home';

const Home = (): ReactElement => (
  <div>
    <Head>
      <title>Earn Alliance</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/earn_management.ico' />
    </Head>
    <HomePage />
  </div>
);

export default Home;
